### ISSUE TITLE
ISA Detection

### ISSUE THREAD

**Issue by Twinklebear** [ospray/tsimd#7]
Currently tsimd just [picks AVX as the target ISA](https://github.com/ospray/tsimd/blob/master/cmake/ispc.cmake#L178) but we might want the default to actually detect the current CPU ISA and pick that, similar to what Embree does in their [CMake](https://github.com/embree/embree/blob/89dedd512fa553d4996a07c6f84f424e894f81d2/common/cmake/check_isa_default.cmake).

**Comment by jeffamstutz** [comment]
The ```TSIMD_BUILD_ISA``` is for enabling the tests + examples to build/run using ISAs older than the user's CPU. However, I think a "native" option would be super easy to implement (and would be the default value). It would simply add ```-march=native``` instead of hand-selected flags.

For tsimd client code, however, that is completely up to the client app for how to handle ISA support. Semi-orthogonal to the issue you mention: I think tsimd would benefit by having a run-time function to detect what ISA is being used, similar to what ```ispc``` does implicitly.

**Comment by jeffamstutz** [comment]
Would you be OK with the native ISA option?

**Comment by Twinklebear** [comment]
Ah you're right, yea since tsimd is header only it's probably not something we actually need to do. A default of native for people building and trying the examples/tests would be good though.

I think the runtime ISA detection could be useful to have available, do you mean something similar to `programCount` in ISPC? Would that be just the `TSIMD_DEFAULT_WIDTH`?

**Comment by jeffamstutz** [comment]
For tsimd kernels, client libraries/applications must figure out a strategy for compiling multiple versions for different ISAs and select which versions to use at runtime based on the detected CPU's features. Thus ```TSIMD_DEFAULT_WIDTH``` would be known for whatever _target_ ISA a tsimd kernel was compiled for, but the proposed function would be fore detecting at runtime CPU features so the library/app can select the right version of the kernel.

The analog here is Embree selecting the right BVH types and ray traversal kerenls based on the detected runtime CPU, despite having many ISA targets compiled into one library.

**Comment by Twinklebear** [comment]
Gotcha, yes that would be useful to have supported in tsimd.

**Comment by jeffamstutz** [comment]
FYI, I implemented ```TSIMD_BUILD_ISA=NATIVE``` as an option (which is now the default)
